apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vivek-pr/airflow-alpine-k8s.git
    targetRevision: codex/set-up-ci-pipeline-for-airflow-helm-chart
    path: helm
    helm:
      valueFiles:
        - values-alpine.yaml
  info:
    - name: Airflow UI
      value: http://airflow.local
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
