apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  source:
    # Use the main branch by default. Change this if you maintain a
    # separate development branch.
    targetRevision: main
  destination:
    namespace: airflow-dev
