name: Build Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install security tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release tar curl
          # hadolint
          curl -L -o hadolint "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64"
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy
          COSIGN_VERSION="v2.2.3"
          curl -L -o cosign "https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64"
          chmod +x cosign
          sudo mv cosign /usr/local/bin/
          KUBESCORE_VERSION="1.17.0"
          curl -L -o kube-score.tar.gz "https://github.com/zegl/kube-score/releases/download/v${KUBESCORE_VERSION}/kube-score_${KUBESCORE_VERSION}_linux_amd64.tar.gz"
          tar -xzf kube-score.tar.gz
          sudo mv kube-score /usr/local/bin/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          tags: airflow-alpine-k8s:latest
          context: .
          file: docker/Dockerfile
      - name: Run local tests
        run: |
          ./tests/test_hadolint.sh
          ./tests/test_packages.sh
          ./tests/test_trivy.sh
          ./tests/test_image_signing.sh
          ./tests/test_security_compliance.sh
      - name: Verify container
        run: docker run --rm airflow-alpine-k8s:latest airflow version

