name: Build Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          tags: airflow-alpine-k8s:latest
          context: .
          file: docker/Dockerfile
      - name: Run local tests
        run: |
          ./tests/test_packages.sh
          ./tests/test_trivy.sh
          ./tests/test_image_signing.sh
          ./tests/test_security_compliance.sh
      - name: Verify container
        run: docker run --rm airflow-alpine-k8s:latest airflow version

